{{- $apiKey := .Values.secrets.apiKey | default (randAlphaNum 32) | b64enc  }}
{{- $mongo :=  .Values.secrets.mongoUrl | b64enc -}}
{{- $oneSignalAppId := .Values.secrets.oneSignalAppId | b64enc -}}
{{- $oneSignalToken := .Values.secrets.oneSignalToken | b64enc -}}
{{- $oneSignalUrl := .Values.secrets.oneSignalUrl | b64enc -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "api-hra-secrets") }}
{{- if $secret }}
{{- $apiKey = index $secret.data "api-key" }}
{{- $mongo = index $secret.data "mongo"}}
{{- $oneSignalAppId = index $secret.data "one-signal-app-id" }}
{{- $oneSignalToken = index $secret.data "one-signal-token" }}
{{- $oneSignalUrl = index $secret.data "one-signal-url" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (include "api-interna-pacientes.fullname" .) | printf "%s-secrets" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-interna-pacientes.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ $apiKey }}
  mongo: {{ $mongo }}
  one-signal-app-id: {{ $oneSignalAppId }}
  one-signal-token: {{ $oneSignalToken }}
  one-signal-url: {{ $oneSignalUrl }}
